CREATE TABLE ADDRESS (
  ID      INT          NOT NULL
                       GENERATED ALWAYS   AS IDENTITY
                       (START WITH 1, INCREMENT BY 1)
                       PRIMARY KEY,
  STREET  VARCHAR(255) NOT NULL,
  STREET2 VARCHAR(255),
  CITY    VARCHAR(255) NOT NULL,
  STATE   VARCHAR(2)   NOT NULL,
  ZIP     VARCHAR(10)  NOT NULL
);



CREATE TABLE USERS (
  ID           INT          NOT NULL
                            GENERATED ALWAYS  AS IDENTITY
                            (START WITH 1, INCREMENT BY 1)
                            PRIMARY KEY,
  USER_NAME     VARCHAR(15) NOT NULL CONSTRAINT users_username_UC UNIQUE,
  FIRST_NAME    VARCHAR(50) NOT NULL,
  LAST_NAME     VARCHAR(50) NOT NULL,
  ACTIVE_SINCE DATE,
  ADDRESS_ID   INT   CONSTRAINT USR_ADDR_FK REFERENCES ADDRESS
);




CREATE TABLE PHONE (
  ID      INT          NOT NULL
                       GENERATED ALWAYS AS IDENTITY
                       (START WITH 1, INCREMENT BY 1)
                       PRIMARY KEY,
  USER_ID INT          CONSTRAINT PHONE_USR_FK REFERENCES USERS,
  label   VARCHAR(255) ,
  phone   VARCHAR(255) NOT NULL
);



               
       